## ```IMDB Dataset of 50K Movie Reviewsm```

In [201]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [202]:
df= pd.read_csv('../Data/IMDB Dataset.csv')
print('Shape :', df.shape)

print('\nColumns :')
print(df.columns)

print('\nData Types :')
print(df.dtypes)

print('\nInfo :')
df.info()

print('\nMissing Values :')
print(df.isnull().sum())

print('\nDuplicate Rows :', df.duplicated().sum())

print('\nStatistical Summary :')
print(df.describe())

print('\nCategorical Summary :')
print(df.describe(include='object'))

print('\nCorrelation Matrix :')
print(df.corr(numeric_only=True))

Shape : (50000, 2)

Columns :
Index(['review', 'sentiment'], dtype='object')

Data Types :
review       object
sentiment    object
dtype: object

Info :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB

Missing Values :
review       0
sentiment    0
dtype: int64

Duplicate Rows : 418

Statistical Summary :
                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

Categorical Summary :
                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

Correlation Matrix :
Empty DataFrame
Columns: []
Index: []

In [203]:
df[df.duplicated()].head(10)

                                                 review sentiment
3537  Quite what the producers of this appalling ada...  negative
3769  My favourite police series of all time turns t...  positive
4391  Beautiful film, pure Cassavetes style. Gena Ro...  positive
6352  If you liked the Grinch movie... go watch that...  negative
6479  I want very much to believe that the above quo...  negative
6672  Sigh. I'm baffled when I see a short like this...  negative
7221  I have always been a huge fan of "Homicide: Li...  positive
7222  There are plenty of comments already posted sa...  negative
7425  The movie was excellent, save for some of the ...  positive
7555  This movie has made me upset! When I think of ...  negative

In [204]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

In [205]:
df['review_length'] = df['review'].apply(len)

df['review_length'].describe()

count    50000.000000
mean      1309.431020
std        989.728014
min         32.000000
25%        699.000000
50%        970.000000
75%       1590.250000
max      13704.000000
Name: review_length, dtype: float64

In [206]:
df['word_count'] = df['review'].apply(lambda x: len(x.split()))

df['word_count'].describe()

count    50000.000000
mean       231.156940
std        171.343997
min          4.000000
25%        126.000000
50%        173.000000
75%        280.000000
max       2470.000000
Name: word_count, dtype: float64

In [207]:
## remove duplicates
df.drop_duplicates(inplace=True)
df.reset_index(drop=True,inplace=True)

In [208]:
df.shape

(49582, 4)

In [209]:
df.head()

,review,sentiment,review_length,word_count
0,One of the other reviewers has mentioned that ...,positive,1761,307
1,A wonderful little production. <br /><br />The...,positive,998,162
2,I thought this was a wonderful way to spend ti...,positive,926,166
3,Basically there's a family where a little boy ...,negative,748,138
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1317,230

In [210]:
df['review'].sample(5, random_state=42).tolist()

['"Soul Plane" is a horrible attempt at comedy that only should appeal people with thick skulls, bloodshot eyes and furry pawns. <br /><br />The plot is not only incoherent but also non-existent, acting is mostly sub sub-par with a gang of highly moronic and dreadful characters thrown in for bad measure, jokes are often spotted miles ahead and almost never even a bit amusing. This movie lacks any structure and is full of racial stereotypes that must have seemed old even in the fifties, the only thing it really has going for it is some pretty ladies, but really, if you want that you can rent something from the "Adult" section. OK?<br /><br />I can hardly see anything here to recommend since you\'ll probably have a lot a better and productive time chasing rats with a sledgehammer or inventing waterproof teabags or whatever.<br /><br />2/10',
 'Guest from the Future tells a fascinating story of time travel, friendship, battle of good and evil -- all with a small budget, child actors, and few special effects. Something for Spielberg and Lucas to learn from. ;) A sixth-grader Kolya "Nick" Gerasimov finds a time machine in the basement of a decrepit building and travels 100 years into the future. He discovers a near-perfect, utopian society where robots play guitars and write poetry, everyone is kind to each other and people enjoy everything technology has to offer. Alice is the daughter of a prominent scientist who invented a device called Mielophone that allows to read minds of humans and animals. The device can be put to both good and bad use, depending on whose hands it falls into. When two evil space pirates from Saturn who want to rule the universe attempt to steal Mielophone, it falls into the hands of 20th century school boy Nick. With the pirates hot on his tracks, he travels back to his time, followed by the pirates, and Alice. Chaos, confusion and funny situations follow as the luckless pirates try to blend in with the earthlings. Alice enrolls in the same school Nick goes to and demonstrates superhuman abilities in PE class. The catch is, Alice doesn\'t know what Nick looks like, while the pirates do. Also, the pirates are able to change their appearance and turn literally into anyone. (Hmm, I wonder if this is where James Cameron got the idea for Terminator...) Who gets to Nick -- and Mielophone -- first? Excellent plot, non-stop adventures, and great soundtrack. I wish Hollywood made kid movies like this one...',
 '"National Treasure" (2004) is a thoroughly misguided hodge-podge of plot entanglements that borrow from nearly every cloak and dagger government conspiracy cliché that has ever been written. The film stars Nicholas Cage as Benjamin Franklin Gates (how precious is that, I ask you?); a seemingly normal fellow who, for no other reason than being of a lineage of like-minded misguided fortune hunters, decides to steal a \'national treasure\' that has been hidden by the United States founding fathers. After a bit of subtext and background that plays laughably (unintentionally) like Indiana Jones meets The Patriot, the film degenerates into one misguided whimsy after another \x96 attempting to create a \'Stanley Goodspeed\' regurgitation of Nicholas Cage and launch the whole convoluted mess forward with a series of high octane, but disconnected misadventures.<br /><br />The relevancy and logic to having George Washington and his motley crew of patriots burying a king\'s ransom someplace on native soil, and then, going through the meticulous plan of leaving clues scattered throughout U.S. currency art work, is something that director Jon Turteltaub never quite gets around to explaining. Couldn\'t Washington found better usage for such wealth during the start up of the country? Hence, we are left with a mystery built on top of an enigma that is already on shaky ground by the time Ben appoints himself the new custodian of this untold wealth. Ben\'s intentions are noble \x96 if confusing. He\'s set on protecting the treasure. For who and when?\x85your guess is as good as mine.<br /><br />But there are a few problems with Ben\'s crusade. First up, his friend, Ian Holmes (Sean Bean) decides that he can\'t wait for Ben to make up his mind about stealing the Declaration of Independence from the National Archives (oh, yeah \x96 brilliant idea!). Presumably, the back of that famous document holds the secret answer to the ultimate fortune. So Ian tries to kill Ben. The assassination attempt is, of course, unsuccessful, if overly melodramatic. It also affords Ben the opportunity to pick up, and pick on, the very sultry curator of the archives, Abigail Chase (Diane Kruger). She thinks Ben is clearly a nut \x96 at least at the beginning. But true to action/romance form, Abby\'s resolve melts quicker than you can say, "is that the Hope Diamond?" The film moves into full X-File-ish mode, as the FBI, mistakenly believing that Ben is behind the theft, retaliate in various benign ways that lead to a multi-layering of action sequences reminiscent of Mission Impossible meets The Fugitive. Honestly, don\'t those guys ever get \'intelligence\' information that is correct? In the final analysis, "National Treasure" isn\'t great film making, so much as it\'s a patchwork rehash of tired old bits from other movies, woven together from scraps, the likes of which would make IL\' Betsy Ross blush.<br /><br />The Buena Vista DVD delivers a far more generous treatment than this film is deserving of. The anamorphic widescreen picture exhibits a very smooth and finely detailed image with very rich colors, natural flesh tones, solid blacks and clean whites. The stylized image is also free of blemishes and digital enhancements. The audio is 5.1 and delivers a nice sonic boom to your side and rear speakers with intensity and realism. Extras include a host of promotional junket material that is rather deep and over the top in its explanation of how and why this film was made. If only, as an audience, we had had more clarification as to why Ben and co. were chasing after an illusive treasure, this might have been one good flick. Extras conclude with the theatrical trailer, audio commentary and deleted scenes. Not for the faint-hearted \x96 just the thick-headed.',
 'OK. First said, I just wanted to check whether this movie has an average rating below or exactly -1. But 5,9. This is sicker than any of the killers\' proceedings -,- . That made me curious what people wrote here.. which in the end made me set up an account to give my 2cents of truth into this "well of delusion" i find here.<br /><br />How dare you guys even MENTION this movie in the same sentences as e.g. Seven? The only thing they got in common is that they show various crime-scenes. That-is-it. And "Best thriller of 1999!" ? have you even watched another movie form that year? Or any other movie in your life at all? 1999 is not a year which people are reminded of by RESURRECTION... what\'s with actual MOVIES like 8mm, Eyes wide shut, Arlington Road, Double Jeopardy? (Theyre actually more a "thriller" than this one could ever be..). Resurrection does not even deserve to be dedicated to A SECOND of 1999.<br /><br />Really, you guys can\'t be serious. I watched that movie yesterday with my girlfriend, highly recommended by a friend of her. A "great film with Christopher Lambert"! ...which I had not yet seen? Hmm.. <br /><br />Well, first look on the Covers: OK, nothing special. At second glimpse you don\'t need to have supernatural powers to be aware that they simply mirrored Lambert\'s head, clipped his nose \'n this&that, then made a fancy negative pattern on top of it, to get the killers image on the COVER. You could even think they had some apprentice eat a gallon of marshmallows just to caption that creepy (booooh! -.- ) mouth.. whatever. Turned it around and the plot starts with.. "it\'s raining in Chicago... blabber blabber". Come on, a six year old could have made that snippet sound more exciting. Now, with this enormous excitement coming from the movies terrific presentation -.- , you absolutely wanna start watching it. Because it can\'t be that bad, it still is Christopher Lambert. That assumption of mine was proved wrong. WIth "proven wrong" i mean it was brutally executed by a deadly mix of the worst imaginable acting ever known to mankind (every actor, but the tops are the "i can do 1-Liners!" police chief, Prudhommes Wife __ actually a better detective than Prudhomme when she recombines several incidents to a yet ABSOLUTELY UNKNOWN hint in the case!!!! -.- __ and .. yes.. Prudhomme himself) featuring a squadron of inhuman fake feelings, logic errors in a 1-minute-cycle, light-years far-fetched conclusions which in my point-of-view represent an insult to any thinking human being and last but not least a camera-man who obviously was a hyperventilating kangaroo. Oh well, and if you do not completely shut down your brains (these aren\'t premises to watch it) then you should know who is who and what is what after max. 30minutes, simply because you know ANY scene after the first. That is thrilling. Thrilling because this movie almost makes you think you can tell the future. <br /><br />The bottom line: This is BY FAR the worst movie I can remember. Trust me, I\'ve seen many horrible movies which in some way were at least only bad attempts or bad copies of another movie. Resurrection however, is the best example on how to fail in every aspect possible. It was so bad that after being shocked by its unimaginably low quality in e-v-e-r-y-t-h-i-n-g, I laughed more often than in any recent comedy, simply because I was fascinated by the crew\'s brazenness to publish such an -extraordinary- film strip. Good thing for Lambert he was in Highlander:Endgame a year later, thus he can be pardoned. ;^O<br /><br />Anyhow, I DO recommend watching this movie to EVERYONE. In the end, we had great fun watching it :^D. I guarantee you, after you completely watched Resurrection (be brave, you can do it!) , you will worship the level of acting in any given daily soap. <br /><br />Or just go \'n watch highlander one more time... that\'s what I\'m gonna do.',
 "I haven't always been a fan, but the show grew on me. It wasn't until after season 5 that I started to see the richness of the show. They finally brought Daniel Jackson's search for his wife to an end and finally most of the Go,ould System Lords were killed by rival Lords, SG-1 or others.<br /><br />Towards Season 5, Stargate SG-1, was beginning to become stale. With the new writers and the close attention by Produer Peter Deleuise, the show became more and more solid.<br /><br />The characters had become stale as well. Colonel Jack O'Neill was the stereotypical hero with emotional baggage. After his son Charlie was killed in a shooting accident with O'Neill's weapon, he had decided to end his own life by going to Abydos in order to face off with the Go'ould RA. The character offers little growth for any actor and actor Richard Dean Anderson chose to play him straight raising emotional barriers to protect himself. only allowing his close friends in.<br /><br />Amanda Tapping joined the cast as Captain Samantha Carter. She was a feminist on the edge, ready to battle any man who would doubt her ability to do her job. Though this character had little area to grow, Tapping has done a great job of concentrating on Carter's strengths. She has taken the time to get a basic understanding of some of the things Carter talks about in order that she can present the character intelligently. <br /><br />Christopher Judge joined the cast playing the alien Teal'c. Teal'c was an alien called the Jaffa. Infant Go'ould, (snake like creatures) would embed themselves into the Jaffa until they had grown to the point when it would be inserted into another life form. The Jaffa would die. Teal'c was the First Prime of Apophis' army. Knowing that Apophis was not a god like Go'ould pretend, he realized the genocide that their armies had wreaked on the galaxy. Finally, having had enough, he and Jack O'Neill freed their team along with quite a few innocent people. After arriving on Earth, he realized that Earth was the planet he was looking for, who would help him fight the Go'ould. Christopher Judge has done quite a bit with a limited character. Teal'c is a wise warrior, much of which he learned was from his teacher Master Bra'tac. The show would not be complete without Master Bra'tac played by Tony Amandola. He is also a rock. In the end, he became adviser to most of SG-1, especially Daniel Jackson. <br /><br />Don S. Davil was there from the beginning playing Major General George Hammand. Davis has done an incredible job with Hammond making him sympathetic and normal. He does his job, has a wife, sons and daughters and grandchildren. You can really say, he is the anchor of the base. Simply, I would die for that man. If not allowed by his superiors to provide troops to support teams off world. He will go himself. He doesn't leave anyone behind.<br /><br />I saved Dr. Daniel Jackson for last, because this character, I believe has grown the most in the ten or eleven years it has been on. In choosing Shanks I don't think the producer realized how strong Shanks would be and now when people talk about Jackson, they don't talk about Spader, they talk about Shanks. In the early years, the Jackson character came off as a whiner. That's why I probably wasn't a fan. As the seasons pasted, the character became stronger. This gave him confidence. In the end, as of season 10, the Jackson character has matured to the point that he has become a self sacrificing hero. He still monitors the groups ethics. He still is lead at providing information that can move any mission forward. Acheaology, History, Culture and Exploration are part of his very being. He is determined. Though a man of peace, he has matured to the point that using his weapons may be the only way to solve a disagreement. <br /><br />Other characters include, most recently: Vala Mal Doran(Claudia Black) and Colonel Cameron Mitchell(Ben Browder), new lead of SG-1. Both actors come from a series called Farscape and why they were put together is any bodies guess. I see little difference between Mitchell and Crichton (Farscape character). Black's character is simply off the wall. Definitely different from her soldier like character Arin Soon."]

### ``` Data Preprocessing```

In [211]:
## remove HTLML TAGS  (<br /><br />)

## import Library
from bs4 import BeautifulSoup
def remove_html(text):
    return BeautifulSoup(text,'html.parser').get_text()

In [212]:
df['review_no_html'] = df['review'].apply(remove_html)

In [213]:
df[['review', 'review_no_html']].head()

,review,review_no_html
0,One of the other reviewers has mentioned that ...,One of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,A wonderful little production. The filming tec...
2,I thought this was a wonderful way to spend ti...,I thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,Basically there's a family where a little boy ...
4,"Petter Mattei's ""Love in the Time of Money"" is...","Petter Mattei's ""Love in the Time of Money"" is..."

In [214]:
print(df['review'].iloc[1])

print("="*100)

print(df['review_no_html'].iloc[1])

A wonderful little production. <br /><br />The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. <br /><br />The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. <br /><br />The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.
====================================================================================================
A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.

In [215]:
## LowerCase
df['review_lower'] =df['review_no_html'].str.lower()

In [216]:
print(df['review_no_html'].iloc[1])

print("="*100)

print(df['review_lower'].iloc[1])

A wonderful little production. The filming technique is very unassuming- very old-time-BBC fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. The actors are extremely well chosen- Michael Sheen not only "has got all the polari" but he has all the voices down pat too! You can truly see the seamless editing guided by the references to Williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. A masterful production about one of the great master's of comedy and his life. The realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. It plays on our knowledge and our senses, particularly with the scenes concerning Orton and Halliwell and the sets (particularly of their flat with Halliwell's murals decorating every surface) are terribly well done.
====================================================================================================
a wonderful little production. the filming technique is very unassuming- very old-time-bbc fashion and gives a comforting, and sometimes discomforting, sense of realism to the entire piece. the actors are extremely well chosen- michael sheen not only "has got all the polari" but he has all the voices down pat too! you can truly see the seamless editing guided by the references to williams' diary entries, not only is it well worth the watching but it is a terrificly written and performed piece. a masterful production about one of the great master's of comedy and his life. the realism really comes home with the little things: the fantasy of the guard which, rather than use the traditional 'dream' techniques remains solid then disappears. it plays on our knowledge and our senses, particularly with the scenes concerning orton and halliwell and the sets (particularly of their flat with halliwell's murals decorating every surface) are terribly well done.

### ```Contraction Expansion```

## Contractions

**Definition:**

> **Contractions are shortened forms of two or more words joined with an apostrophe (`'`). In NLP, they are expanded into their full forms during text preprocessing to preserve the original meaning and improve model performance.**

**Examples:**

| Contraction | Expanded Form |
|-------------|---------------|
| don't | do not |
| can't | cannot |
| I'm | I am |
| it's | it is |
| you're | you are |

**One-line Exam Note:**

> **Contraction Expansion is the process of converting shortened words (e.g., "don't") into their complete forms (e.g., "do not") before NLP processing.**

In [217]:
## install COntraction
#  !pip install contractions

In [218]:
import contractions

def expand_contractions(text):
    return contractions.fix(text)

In [219]:
df['review_expanded'] = df['review_lower'].apply(expand_contractions)

In [220]:
print(df['review_lower'].iloc[0])

print("="*100)

print(df['review_expanded'].iloc[0])

one of the other reviewers has mentioned that after watching just 1 oz episode you'll be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. em city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows wouldn't dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz doesn't mess around. the first episode i ever saw struck me as so nasty it was surreal, i couldn't say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who'll be sold out for a nickel, inmates who'll kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....thats if you can get in touch with your darker side.
====================================================================================================
one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. them city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows would not dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz does not mess around. the first episode i ever saw struck me as so nasty it was surreal, i could not say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who will be sold out for a nickel, inmates who will kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....that is if you can get in touch with your darker side.

In [221]:
## VERIFY REVIEW_EXPANDED

df['review_expanded'].str.contains(r'http|www', case=False, regex=True).sum()

np.int64(243)

In [222]:
## Inspect
for review in df[df['review_expanded'].str.contains(r'http|www', case=False, regex=True)]['review_expanded'].head(5):
    print(review)
    print("="*120)

first of all, let us get a few things straight here: a) i am an anime fan- always has been as a matter of fact (i used to watch speed racer all the time in preschool). b) i do like several b-movies because they are hilarious. c) i like the godzilla movies- a lot.moving on, when the movie first comes on, it seems like it is going to be your usual b-movie, down to the crappy fx, but all a sudden- boom! the anime comes on! this is when the movie goes wwwaaaaayyyyy downhill.the animation is very bad & cheap, even worse than what i remember from speed racer, for crissakes! in fact, it is so cheap, one of the few scenes from the movie i "vividly" remember is when a bunch of kids run out of a school... & it is the same kids over & over again! the fx are terrible, too; the dinosaurs look worse than godzilla. in addition, the transition to live action to animation is unorganized, the dialogue & voices(especially the english dub that i viewed) was horrid & i was begging my dad to take the tape out of the dvd/ vhs player; the only thing that kept me surviving was cracking out jokes & comments like the robots & joel/mike on mst3k (you pick the season). honestly, this is the only way to barely enjoy this movie & survive it at the same time.heck, i am planning to show this to another fellow otaku pal of mine on halloween for a b-movie night. because it is stupid, pretty painful to watch & unintentionally hilarious at the same time, i am giving this movie a 3/10, an improvement from the 0.5/10 i was originally going to give it.(according to my grading scale: 3/10 means pretty much both boring & bad. as fun as counting to three unless you find a way to make fun of it, then it will become as fun as counting to 15.)
========================================================================================================================
awwww, i just love this movie to bits. me and my cousins enjoy this movie a lot and i am just such a huge fan!!! i hope they bring the tv series out on dvd soon. come to mention it, i have not see the tv show in a long time. such geart times! where i come from australia the chipmunk adventure is only known by people in their late teens and adult years which is kind of sad because the young kids do not know what there missing.the songs in this film are ace the ones i love the most boys/girls of rock n'roll, diamond dolls and the song that ls sure to make you want to cry my mother.this film is sure to excite both young and old get the chipmunk adventure today!!! 10 out of 10, such an excellent movie.
========================================================================================================================
mario lewis of the competitive enterprise institute has written a definitive 120-page point-by-point, line-by-line refutation of this mendacious film, which should be titled a convenient lie. the website address where his debunking report, which is titled "a skeptic's guide to an inconvenient truth" can be found at is :www.cei.org. a shorter 10-page version can be found at: www.cei.org/pdf/5539.pdf once you read those demolitions, you will realize that alleged "global warming" is no more real or dangerous than the y2k scare of 1999, which gore also endorsed, as he did the pseudo-scientific film the day after tomorrow, which was based on a book written by alleged ufo abductee whitley strieber. as james "the amazing" randi does to psychics, and philip klass does to ufos, and gerald posner does to jfk conspir-idiocy theories, so does mario lewis does to al gore's movie and the whole "global warming" scam.
========================================================================================================================
following directly from where the story left off in part one, the second half which sets about telling the inevitable downfall and much more grim side of the man's legacy is exactly as such. in direct contrast to the first feature, part two represents a shift from che the pride and glory of a revolutionised country, to chestruggling liberator of a country to which he has no previous ties. the change of setting is not just aesthetic; from the autumn and spring greys of the woodlands comes a change of tone and heart to the feature, replacing the optimism of the predecessor with a cynical, battered and bruised reality aligned to an all new struggle. yet, as che would go on to say himselfsuch a struggle is best told exactly as thata struggle. while part one certainly helped document that initial surge to power that the revolutionary guerrilla acquired through just that, part two takes a much more refined, callous and bleak segment of che's life and ambition, and gives it an assertive portrayal that is both poignant and tragic in a tangible, easy to grasp manner.while the movie's tone in some regards does stray off and differ quite drastically from part one however, there still remains that same documented approach taken a month ago that avoids melodrama and fabrication as much as possible. this somewhat distant, cold approach to telling che's story and struggle will no doubt turn some viewers off; indeed, i still remain reserved about whether or not the feature itself should have been named after one manif anything, the entirety of che, taken as a whole, delivers a tale that goes beyond mere biography and instead documents a man's struggle alongside those who helped carry him along the way. by no means does soderbergh try to paint a humanistic portrait here akin to what hirschbiegel did with der untergang half a decade ago (excuse the ironic contrast); che is a slow moving, reserved and meditative approach to telling a history lesson that just happens to be narrated by the one man who arguably- conducted the whole thing.yet by moving from the lush green landscapes of cuba and retreating to the bleak, decaying backdrop of bolivia for part two, the story does inevitably take on a distinctly contrasting tone that does not feel too disjointed from its predecessor, but does enough to give it its own reference points. here, the basic structure of part one is echoed backthere is the initial struggle, the battles, the fallen comrades and the recruiting of those to replace them, all the while we see some glimpses of the man behind the movement. yet, as anyone with the vaguest idea of the actual history behind the feature will know, part two is destined to end on a much more underwhelming, and disquieting note. this difference, in combination with the similarities to part one, make a compelling and memorable whole; by all means, both could be digested one their own (and kudos to soderbergh for achieving as such) and enjoyed as they are, but taken as one statement, che delivers exactly what it sets out to achieve.indeed, everything that made part one the treat that it was one month prior is still evident here from the subtle yet engrossing performances from the central cast to the slow building, realistically structured combat scenesthe drama inherent to the characters on screen is just as vague and indiscernible, but with a feature such as this, part two once again proves that avoiding such elements do not necessarily hurt a film when there is enough plot and reflection on other elements to keep the viewer engaged. in fact, upon writing this review i was at odds as to whether or not to simply add a paragraph or two to my initial review for part one, and title the review as a whole, yet i felt that to do so would only serve to disillusion those who may sit down to watch the entirety of both films consecutively.with that said, i cannot rightfully decree whether or not che holds up to the task of engaging an audience for its sprawling four hour plus runtime, but upon viewing both segments i can at least attest to each part's ability to do just that. with a reflective, intricate screenplay combined with endlessly mesmerising photography and nuanced performances that do justice to the movie's characters without drawing attention to themselves, che part two is every bit as compelling and rewarding as its predecessor, but this time with a tragic but uplifting, reaffirming conclusion fit for the history pages of film.- a review by jamie robert ward (http://www.invocus.net)
========================================================================================================================
possible spoilers, perhaps. i must say that "cinderella ii: dreams come true" is one of the worst movies ever made. first of all, the movie was made during the height of disney's sequel rampage. it was created around the same time as "the little mermaid ii," "the jungle book ii," and "peter pan ii," all of which were disservices to their original film classics. (disney also made "the hunchback of notre dame ii" and "atlantis ii," but i am going to drop that topic because their original movies were never really classics in the first place.") let me go ahead and say that i am an avid supporter of good disney films, and i absolutely adore the original disney "cinderella." the sequel to "cinderella," however, was a waste of time. the character of cinderella in the sequel was so very unlike the original girl that i grew up watching. in the original, cinderella was kind and loving. the new cinderella had very out-of-character moments with current-era phrasing like, "i am going to do this banquet my way!" let me also tell you that new cinderella (as i have affectionately named her) says, "ewww!" that is the anti-cinderella. i try to find the best in people, but in the sequel, anastasia, one of the stepsisters, is good! what the heck? why? they made it all out to be like lady tremaine and drizella are just horrible family members for poor little anastasia. my question to the world: did the people at disney watch the original "cinderella" when making this sequel? well, it surely does not seem so. if i remember correctly, anastasia was just as abusive to cinderella as drizella and lady tremaine. i am all for redemption and forgiveness, but there was no point of redemption for anastasia in this movie. in the first one, anastasia was evil. in the second one, she is good. one just cannot leave a story like this. i hope disney realizes that this movie, among other movies, is shaming walt disney's name. perhaps now that michael eisner is gone, things will start shaping up around the house of mouse.
========================================================================================================================

In [223]:
## REMOVE URL'S
import re
def remove_url(text):
    return re.sub(r'https?://\S+|www\.\S+', '', text)

In [224]:
df['review_no_url'] = df['review_expanded'].apply(remove_url)

In [225]:
df[['review_expanded', 'review_no_url']].head()

,review_expanded,review_no_url
0,one of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,a wonderful little production. the filming tec...,a wonderful little production. the filming tec...
2,i thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,basically there is a family where a little boy...,basically there is a family where a little boy...
4,"petter mattei's ""love in the time of money"" is...","petter mattei's ""love in the time of money"" is..."

In [226]:
## verify
df['review_no_url'].str.contains(r'http|www', case=False, regex=True).sum()

np.int64(50)

In [227]:
for review in df[df['review_no_url'].str.contains(r'http|www', case=False, regex=True)]['review_no_url'].head(5):
    print(review)
    print("="*120)

first of all, let us get a few things straight here: a) i am an anime fan- always has been as a matter of fact (i used to watch speed racer all the time in preschool). b) i do like several b-movies because they are hilarious. c) i like the godzilla movies- a lot.moving on, when the movie first comes on, it seems like it is going to be your usual b-movie, down to the crappy fx, but all a sudden- boom! the anime comes on! this is when the movie goes wwwaaaaayyyyy downhill.the animation is very bad & cheap, even worse than what i remember from speed racer, for crissakes! in fact, it is so cheap, one of the few scenes from the movie i "vividly" remember is when a bunch of kids run out of a school... & it is the same kids over & over again! the fx are terrible, too; the dinosaurs look worse than godzilla. in addition, the transition to live action to animation is unorganized, the dialogue & voices(especially the english dub that i viewed) was horrid & i was begging my dad to take the tape out of the dvd/ vhs player; the only thing that kept me surviving was cracking out jokes & comments like the robots & joel/mike on mst3k (you pick the season). honestly, this is the only way to barely enjoy this movie & survive it at the same time.heck, i am planning to show this to another fellow otaku pal of mine on halloween for a b-movie night. because it is stupid, pretty painful to watch & unintentionally hilarious at the same time, i am giving this movie a 3/10, an improvement from the 0.5/10 i was originally going to give it.(according to my grading scale: 3/10 means pretty much both boring & bad. as fun as counting to three unless you find a way to make fun of it, then it will become as fun as counting to 15.)
========================================================================================================================
awwww, i just love this movie to bits. me and my cousins enjoy this movie a lot and i am just such a huge fan!!! i hope they bring the tv series out on dvd soon. come to mention it, i have not see the tv show in a long time. such geart times! where i come from australia the chipmunk adventure is only known by people in their late teens and adult years which is kind of sad because the young kids do not know what there missing.the songs in this film are ace the ones i love the most boys/girls of rock n'roll, diamond dolls and the song that ls sure to make you want to cry my mother.this film is sure to excite both young and old get the chipmunk adventure today!!! 10 out of 10, such an excellent movie.
========================================================================================================================
possible spoilers, perhaps. i must say that "cinderella ii: dreams come true" is one of the worst movies ever made. first of all, the movie was made during the height of disney's sequel rampage. it was created around the same time as "the little mermaid ii," "the jungle book ii," and "peter pan ii," all of which were disservices to their original film classics. (disney also made "the hunchback of notre dame ii" and "atlantis ii," but i am going to drop that topic because their original movies were never really classics in the first place.") let me go ahead and say that i am an avid supporter of good disney films, and i absolutely adore the original disney "cinderella." the sequel to "cinderella," however, was a waste of time. the character of cinderella in the sequel was so very unlike the original girl that i grew up watching. in the original, cinderella was kind and loving. the new cinderella had very out-of-character moments with current-era phrasing like, "i am going to do this banquet my way!" let me also tell you that new cinderella (as i have affectionately named her) says, "ewww!" that is the anti-cinderella. i try to find the best in people, but in the sequel, anastasia, one of the stepsisters, is good! what the heck? why? they made it all out to be like lady tremaine and drizella are just horrible family members for poor little anastasia. my question to the world: did the people at disney watch the original "cinderella" when making this sequel? well, it surely does not seem so. if i remember correctly, anastasia was just as abusive to cinderella as drizella and lady tremaine. i am all for redemption and forgiveness, but there was no point of redemption for anastasia in this movie. in the first one, anastasia was evil. in the second one, she is good. one just cannot leave a story like this. i hope disney realizes that this movie, among other movies, is shaming walt disney's name. perhaps now that michael eisner is gone, things will start shaping up around the house of mouse.
========================================================================================================================
i have just recently purchased collection one of this awesome series and even after just watching three episodes, i still am mesmerized by sleek styling of the animation and the slow, yet thoughtful actions of the story-telling. i am still a fan.....with some minor pains.though this installment into the gundam saga is very cool and has what the previous series had-a stylish satiric way of telling about the wrongs of war and not letting go of the need to have control or power over everything(sound familiar?), i have to say that this one gets a bit too mellow-dramatic on continuing to explain the lives of the main characters and their incessant need to belly-ache about every thing that happens and what they need to do to stop the oz group from succeeding in their plans(especially the character called wufei...i mean he whines more than an american character on a soap opera. get a counselor,will ya?)besides for the over-exaggerated drama(i think that mostly comes from the dubbing of the english voice actors), this series is still very exciting and will still captivate me once again. i mean it can always be worse. it could be like the recent installment, seed......eeeewwww, talk about mellow-dramatic....i will chat about that one later.
========================================================================================================================
it is finally coming out. the first season will be available march 2007. it is currently airing on abc family from 4-5 pm eastern time monday through friday. the last episode will air on december 19th at 4:30. i missed it the first 100 times around. i wish i could buy the whole series right now. who does she pick? i have to write 10 lines in order to reply to the first comment. what am i going to say. la da da de de. la da da de de nope only up to 8 how do i get to 9 almost almost awww 9 now i need 10 - 1, 2, 3, 4, 5, 6, 7, i missed counted this is only number 8. punky brewster is pretty awesome too. almost to 10 almost awwwwww.
========================================================================================================================

 ```Special Character Removal```

In [228]:
import re
def remove_special_characters(text):
    text = re.sub(r'[^a-zA-Z0-9\s]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

In [229]:
df['review_clean'] = df['review_no_url'].apply(remove_special_characters)

In [230]:
print(df['review_no_url'].iloc[0])

print("="*120)

print(df['review_clean'].iloc[0])

one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked. they are right, as this is exactly what happened with me.the first thing that struck me about oz was its brutality and unflinching scenes of violence, which set in right from the word go. trust me, this is not a show for the faint hearted or timid. this show pulls no punches with regards to drugs, sex or violence. its is hardcore, in the classic use of the word.it is called oz as that is the nickname given to the oswald maximum security state penitentary. it focuses mainly on emerald city, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. them city is home to many..aryans, muslims, gangstas, latinos, christians, italians, irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.i would say the main appeal of the show is due to the fact that it goes where other shows would not dare. forget pretty pictures painted for mainstream audiences, forget charm, forget romance...oz does not mess around. the first episode i ever saw struck me as so nasty it was surreal, i could not say i was ready for it, but as i watched more, i developed a taste for oz, and got accustomed to the high levels of graphic violence. not just violence, but injustice (crooked guards who will be sold out for a nickel, inmates who will kill on order and get away with it, well mannered, middle class inmates being turned into prison bitches due to their lack of street skills or prison experience) watching oz, you may become comfortable with what is uncomfortable viewing....that is if you can get in touch with your darker side.
========================================================================================================================
one of the other reviewers has mentioned that after watching just 1 oz episode you will be hooked they are right as this is exactly what happened with me the first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the word it is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda them city is home to many aryans muslims gangstas latinos christians italians irish and more so scuffles death stares dodgy dealings and shady agreements are never far away i would say the main appeal of the show is due to the fact that it goes where other shows would not dare forget pretty pictures painted for mainstream audiences forget charm forget romance oz does not mess around the first episode i ever saw struck me as so nasty it was surreal i could not say i was ready for it but as i watched more i developed a taste for oz and got accustomed to the high levels of graphic violence not just violence but injustice crooked guards who will be sold out for a nickel inmates who will kill on order and get away with it well mannered middle class inmates being turned into prison bitches due to their lack of street skills or prison experience watching oz you may become comfortable with what is uncomfortable viewing that is if you can get in touch with your darker side

###  ```Tokenization```
``
Tokenization is the process of breaking text into smaller pieces called tokens (words, subwords, or characters) so that a machine learning model can understand and process the text.``

import nltk

nltk.download('punkt')

nltk.download('punkt_tab')   # agar latest NLTK version ho

In [231]:
from nltk.tokenize import word_tokenize
df['tokens'] = df['review_clean'].apply(word_tokenize)

In [232]:
df[['review_clean', 'tokens']].head()

,review_clean,tokens
0,one of the other reviewers has mentioned that ...,"[one, of, the, other, reviewers, has, mentione..."
1,a wonderful little production the filming tech...,"[a, wonderful, little, production, the, filmin..."
2,i thought this was a wonderful way to spend ti...,"[i, thought, this, was, a, wonderful, way, to,..."
3,basically there is a family where a little boy...,"[basically, there, is, a, family, where, a, li..."
4,petter mattei s love in the time of money is a...,"[petter, mattei, s, love, in, the, time, of, m..."

### 7```: Stopword Removal.```

In [233]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))

keep_words = {
    'not',
    'no',
    'nor',
    'very'
}

stop_words = stop_words - keep_words

df['tokens'] = df['tokens'].apply(
    lambda words: [word for word in words if word not in stop_words]
)

In [234]:
df[['review_clean','tokens']].head()

,review_clean,tokens
0,one of the other reviewers has mentioned that ...,"[one, reviewers, mentioned, watching, 1, oz, e..."
1,a wonderful little production the filming tech...,"[wonderful, little, production, filming, techn..."
2,i thought this was a wonderful way to spend ti...,"[thought, wonderful, way, spend, time, hot, su..."
3,basically there is a family where a little boy...,"[basically, family, little, boy, jake, thinks,..."
4,petter mattei s love in the time of money is a...,"[petter, mattei, love, time, money, visually, ..."

### ```8: Lemmatization```

Lemmatization is the process of converting a word to its base (dictionary) form (lemma) by considering its meaning and grammar.

import nltk

nltk.download('wordnet')

nltk.download('omw-1.4')

In [235]:
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

## aply
df['lemmas'] = df['tokens'].apply(
    lambda words:[lemmatizer.lemmatize(word) for word in words]
)

In [236]:
df[['tokens', 'lemmas']].head()

,tokens,lemmas
0,"[one, reviewers, mentioned, watching, 1, oz, e...","[one, reviewer, mentioned, watching, 1, oz, ep..."
1,"[wonderful, little, production, filming, techn...","[wonderful, little, production, filming, techn..."
2,"[thought, wonderful, way, spend, time, hot, su...","[thought, wonderful, way, spend, time, hot, su..."
3,"[basically, family, little, boy, jake, thinks,...","[basically, family, little, boy, jake, think, ..."
4,"[petter, mattei, love, time, money, visually, ...","[petter, mattei, love, time, money, visually, ..."

In [237]:
## converrt Tokens into sentance
df['clean_review'] = df['lemmas'].apply(' '.join)

In [238]:
df[['review', 'clean_review']].head()

,review,clean_review
0,One of the other reviewers has mentioned that ...,one reviewer mentioned watching 1 oz episode h...
1,A wonderful little production. <br /><br />The...,wonderful little production filming technique ...
2,I thought this was a wonderful way to spend ti...,thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,basically family little boy jake think zombie ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter mattei love time money visually stunnin...

### ```Step 9: TF-IDF (Term Frequency - Inverse Document Frequency)```

TF-IDF is a feature extraction technique that converts text into numerical vectors by assigning higher weights to words that are frequent in a document but rare across the entire corpus.

In [239]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=50000,
    min_df=5,
    max_df=0.8,
    ngram_range=(1,2)
)
X = tfidf.fit_transform(df['clean_review'])
y = df['sentiment']

In [240]:
print(X.shape)
print(y.shape)

(49582, 50000)
(49582,)

In [241]:
## vocabulary size
len(tfidf.vocabulary_)

50000

In [242]:
list(tfidf.get_feature_names_out())[:20]

['00',
 '000',
 '000 00',
 '000 000',
 '000 dollar',
 '000 year',
 '007',
 '01',
 '02',
 '05',
 '06',
 '07',
 '08',
 '10',
 '10 000',
 '10 10',
 '10 15',
 '10 20',
 '10 acting',
 '10 best']

### ```Train Test Split```

In [243]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,stratify=y
)

In [244]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(39665, 50000)
(9917, 50000)
(39665,)
(9917,)

## Model Training

### ```Logistic Regression```

In [245]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(  random_state=42,
    max_iter=1000
)

In [246]:
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [248]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("="*50)
print("Logistic Regression Results")
print("="*50)

print(f"Accuracy : {accuracy_score(y_test, y_pred):.4f}")
print(f"Precision: {precision_score(y_test, y_pred, pos_label='positive'):.4f}")
print(f"Recall   : {recall_score(y_test, y_pred, pos_label='positive'):.4f}")
print(f"F1 Score : {f1_score(y_test, y_pred, pos_label='positive'):.4f}")

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

==================================================
Logistic Regression Results
==================================================
Accuracy : 0.9043
Precision: 0.8951
Recall   : 0.9168
F1 Score : 0.9058

Confusion Matrix
[[4405  535]
 [ 414 4563]]

Classification Report
              precision    recall  f1-score   support

    negative       0.91      0.89      0.90      4940
    positive       0.90      0.92      0.91      4977

    accuracy                           0.90      9917
   macro avg       0.90      0.90      0.90      9917
weighted avg       0.90      0.90      0.90      9917

In [251]:
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    AdaBoostClassifier,
    GradientBoostingClassifier
)

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000, random_state=42),
    "Multinomial NB": MultinomialNB(),
    "Linear SVM": LinearSVC(random_state=42),
    "Decision Tree": DecisionTreeClassifier(random_state=42),
    "Random Forest": RandomForestClassifier(random_state=42),
    "Extra Trees": ExtraTreesClassifier(random_state=42),
    "AdaBoost": AdaBoostClassifier(random_state=42),
    "Gradient Boosting": GradientBoostingClassifier(random_state=42)
}

from sklearn.metrics import accuracy_score, f1_score

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    results.append({
        "Model": name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred, pos_label="positive")
    })

In [252]:
import pandas as pd

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(
    by="Accuracy",
    ascending=False
)

results_df

                 Model  Accuracy  F1 Score
2           Linear SVM  0.908642  0.909346
0  Logistic Regression  0.904306  0.905806
1       Multinomial NB  0.888777  0.889997
5          Extra Trees  0.878693  0.879059
4        Random Forest  0.865282  0.866159
7    Gradient Boosting  0.813552  0.824656
6             AdaBoost  0.752647  0.767466
3        Decision Tree  0.726631  0.727456

### ``` PERFROM HyperParameterTunning on Top Three Models```

### ```1️⃣ Logistic Regression```

In [254]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000, random_state=42)

param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l2"],
    "solver": ["lbfgs"]
}

In [255]:
grid_lr = GridSearchCV(
    estimator=lr,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)
grid_lr.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(max_iter=1000, random_state=42),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10], 'penalty': ['l2'],
                         'solver': ['lbfgs']},
             scoring='accuracy')

In [256]:
print("Best Parameters:", grid_lr.best_params_)
print("Best CV Score :", grid_lr.best_score_)

Best Parameters: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
Best CV Score : 0.9056599016765411

In [257]:
best_lr = grid_lr.best_estimator_

y_pred = best_lr.predict(X_test)

print("Test Accuracy:", accuracy_score(y_test, y_pred))

Test Accuracy: 0.9100534435817283

### ```2.Linear SVM Tuning```

In [258]:
from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV

svm = LinearSVC(random_state=42)

param_grid = {
    "C": [0.01, 0.1, 1, 10]
}

grid_svm = GridSearchCV(
    estimator=svm,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_svm.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LinearSVC(random_state=42), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10]}, scoring='accuracy')

In [259]:
print("Best Parameters:", grid_svm.best_params_)
print("Best CV Score:", grid_svm.best_score_)
best_svm = grid_svm.best_estimator_

y_pred = best_svm.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Best Parameters: {'C': 1}
Best CV Score: 0.9041976553636708
Accuracy: 0.9086417263285268

### ```3.Multinomial Naive Bayes```

In [261]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()

param_grid = {
    "alpha": [0.01, 0.1, 0.5, 1, 2]
}

grid_nb = GridSearchCV(
    estimator=nb,
    param_grid=param_grid,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_nb.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.01, 0.1, 0.5, 1, 2]}, scoring='accuracy')

In [262]:
print("Best Parameters:", grid_nb.best_params_)
print("Best CV Score:", grid_nb.best_score_)
best_nb = grid_nb.best_estimator_

y_pred = best_nb.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Best Parameters: {'alpha': 0.5}
Best CV Score: 0.8841800075633429
Accuracy: 0.8879701522637895

## ``Save Best Model``

In [263]:
import joblib

joblib.dump(best_lr, "sentiment_model.pkl")
joblib.dump(tfidf, "tfidf_vectorizer.pkl")

['tfidf_vectorizer.pkl']

## ```Predications ```

In [267]:
def predict(review):
    review = remove_html(review)
    review = review.lower()
    review = contractions.fix(review)
    review = remove_url(review)
    review = remove_special_characters(review)

    tokens = word_tokenize(review)
    tokens = [word for word in tokens if word not in stop_words]
    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    review = " ".join(tokens)

    review = tfidf.transform([review])

    return best_lr.predict(review)[0]

In [275]:
predict("Terrible acting, horrible screenplay and pathetic direction. I regret watching it.")

'negative'